version: '2.1'
services:
  api:
    container_name: tictactoe_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/opt/tictactoe
    ports:
      - '5000:5000'
    command: carton exec plackup -r -R lib bin/app.psgi
